name: ''
description: ''
inputs:
  BUILD:
    required: false
    description: ""
    default: "false"
  PARAMETERS_FILE:
    required: false
    description: ""
    default: "./.github/ci/parameters.json"
  SERVICE_PRINCIPAL_ID:
    required: true
    description: ""
  SERVICE_PRINCIPAL_PASSWORD:
    required: true
    description: ""

runs:
  using: "composite"
  steps:
    - name: Build image
      if: ${{ inputs.BUILD == 'true' }}
      shell: bash
      run: |
        touch .env
        docker build \
          --file ${{ inputs.DOCKER_COMPOSE_FILE }} \
          -t ghcr.io/torqit/pimcore-azure-provisioning:2 \
          ../../

    - name: Log in to Azure via service principal
      shell: bash
      run: |
        docker run
          --env TENANT=$(jq -r '.parameters.tenantId.value' ${{ inputs.PARAMETERS_FILE }})
          --env SERVICE_PRINCIPAL_ID=${{ inputs.SERVICE_PRINCIPAL_ID }}
          --env SERVICE_PRINCIPAL_PASSWORD=${{ inputs.SERVICE_PRINCIPAL_PASSWORD }}
          --entrypoint "/bin/bash" \
          ghcr.io/torqit/pimcore-azure-provisioning:2 \
          -c '
            az login --tenant $TENANT \
              --service-principal \
                --username $SERVICE_PRINCIPAL_ID \
                --password $SERVICE_PRINCIPAL_PASSWORD
          '