name: Create an Azure Resource Group 

on:
  pull_request:

concurrency: 
  group: ${{ github.repository }}__${{ github.ref }}
  cancel-in-progress: true

env:
  PARAMETERS_FILE: ./.github/parameters.json

jobs:
  name:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - $PARAMETERS_FILE:/azure/parameters.json
    steps:
      - name: Log in to Azure using Service Principal
        run: |
          az login \
            --tenant $(jq -r '.parameters.tenantId.value' $PARAMETERS_FILE)
            --service-principal \
              --username ${{ secrets.SERVICE_PRINCIPAL_ID }} \
              --password ${{ secrets.SERVICE_PRINCIPAL_PASSWORD }}

      # - name: On opening of the PR, create the Resource Group
      #   if: github.event.action == 'opened'
      #   run: |
          
        
      # TODO if PR just created, create Resource Group
      # TODO deploy changes to resource group
      # TODO when PR is closed, delete Resource Group