name: Back up Azure MySQL database

on:
  workflow_dispatch:
  pull_request:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  container-apps-build-and-deploy:
    uses: TorqIT/pimcore-github-actions-workflows/.github/workflows/azure-mysql-backup.yml@db-backup
    permissions:
      actions: read
      contents: read
    with:
      ENVIRONMENT: test
    secrets:
      SERVICE_PRINCIPAL_ID: ${{ secrets.SERVICE_PRINCIPAL_ID }}
      SERVICE_PRINCIPAL_PASSWORD: ${{ secrets.SERVICE_PRINCIPAL_PASSWORD }}
      AZURE_MYSQL_PASSWORD: ${{ secrets.AZURE_MYSQL_PASSWORD }}