name: Tear down Azure resources based on a given parameters file

on:
  workflow_call:
    inputs:
      SERVICE_PRINCIPAL_ID:
        required: true
        type: string
        description: "Azure Service Principal ID with permissions to deploy resources to the target subscription and resource group"
      PARAMETERS_FILE:
        required: true
        type: string
        description: "Path to the parameters file containing the necessary parameters for provisioning the Azure environment"
    secrets:
      SERVICE_PRINCIPAL_PASSWORD:
        required: true
        description: "Azure Service Principal password"

concurrency:
  group: ${{ github.repository }}__${{ github.ref }}-ci-close
  cancel-in-progress: true

jobs:
  tear-down-azure-resources:
    name: Tear down CI Azure resources
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Get workflow version
        id: workflow-version
        uses: canonical/get-workflow-version-action@b21f2a1dad0467fd79081fa16dad4f4935fc6253 # v1
        with:
          repository-name: TorqIT/pimcore-azure-provisioning
          file-name: tear-down-azure-resources.yml
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout workflow repository to use composite actions
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          repository: TorqIT/pimcore-azure-provisioning
          ref: ${{ steps.workflow-version.outputs.sha }}
          path: reusable-workflow
          fetch-depth: 1

      - name: Build and start container, and log in to Azure
        uses: ./reusable-workflow/.github/actions/build-start-and-login
        with:
          BUILD_IMAGE: "true"
          SERVICE_PRINCIPAL_ID: ${{ inputs.SERVICE_PRINCIPAL_ID }}
          SERVICE_PRINCIPAL_PASSWORD: ${{ secrets.SERVICE_PRINCIPAL_PASSWORD }}
          PARAMETERS_FILE: ${{ inputs.PARAMETERS_FILE }}

      - name: Delete Resource Group
        continue-on-error: true
        run: |
          touch .env
          RESOURCE_GROUP=$(jq -r '.parameters.resourceGroupName.value' ${{ inputs.PARAMETERS_FILE }}) >> .env
          docker exec azure bash -c '\
              az group delete \
                --name $RESOURCE_GROUP \
                --yes
          '

      - name: Purge Key Vault
        run: |
          KEY_VAULT=$(jq -r '.parameters.keyVaultName.value' ${{ inputs.PARAMETERS_FILE }}) >> .env
          docker exec azure bash -c '\
              az keyvault purge \
                --name $KEY_VAULT
          '
